create table journey
(
    id                   int generated by default as identity,
    departure            timestamp        not null,
    return_date          timestamp        not null,
    departure_station_id int              not null,
    departure_station    varchar(100)     not null,
    return_station_id    int              not null,
    return_station       varchar(100)     not null,
    distance             double precision not null,
    duration             double precision not null
);

create table station
(
    fid             int           not null primary key,
    station_id      int           not null,
    station_name_fi varchar(100)  not null,
    station_name_sw varchar(100)  not null,
    station_name_en varchar(100)  not null,
    address_fi      varchar(100)  not null,
    address_sw      varchar(100)  not null,
    city_fi         varchar(100)  not null,
    city_sw         varchar(100)  not null,
    operator        varchar(100)  not null,
    capacity        int           not null,
    coordinate_x    decimal(9, 6) not null,
    coordinate_y    decimal(8, 6) not null
);